Furniture = {
    {
        name = 'Cadeiras',
        title = 'Cadeiras', -- Título do menu
        desc = "Ver cadeiras variadas",
        { propModel = "p_chair20x",        displayName = "Cadeira Vermelha Estampada",   costToBuy = 20, sellFor = 18 },
        { propModel = "p_chair38x",        displayName = "Cadeira Amarela Elegante",     costToBuy = 20, sellFor = 18 },
        { propModel = "p_chairdining01x",  displayName = "Cadeira Branca Elegante",      costToBuy = 20, sellFor = 18 },
        { propModel = "p_chair06x",        displayName = "Cadeira Envernizada",          costToBuy = 15, sellFor = 13 },
        { propModel = "p_diningchairs01x", displayName = "Cadeira com Apoio de Braços",  costToBuy = 15, sellFor = 13 },
        { propModel = "p_windsorchair03x", displayName = "Cadeira Marrom",               costToBuy = 15, sellFor = 13 },
        { propModel = "p_chair02x",        displayName = "Cadeira Azul Antiga",          costToBuy = 15, sellFor = 13 },
        { propModel = "s_bfchair04x",      displayName = "Cadeira de Madeira",           costToBuy = 15, sellFor = 13 },
        { propModel = "p_chair_cs05x",     displayName = "Cadeira Polida",               costToBuy = 15, sellFor = 13 },
        { propModel = "p_chairfolding02x", displayName = "Cadeira Dobrável",             costToBuy = 5,  sellFor = 4 },
        { propModel = "p_chair_crate02x",  displayName = "Caixote de Madeira",           costToBuy = 3,  sellFor = 2 },
        { propModel = "p_chairdesk02x",    displayName = "Poltrona de Couro Vermelha",   costToBuy = 40, sellFor = 38 },
        { propModel = "p_chairwicker02x",  displayName = "Poltrona de Vime",             costToBuy = 25, sellFor = 23 },
        { propModel = "p_chairrocking02x", displayName = "Cadeira de Balanço",           costToBuy = 18, sellFor = 16 },
        { propModel = "p_stool07x",        displayName = "Banco Envernizado",            costToBuy = 15, sellFor = 13 },
        { propModel = "p_stool01x",        displayName = "Banco de Madeira",             costToBuy = 12, sellFor = 11 },
        { propModel = "p_stool03x",        displayName = "Banco Gastado",                costToBuy = 5,  sellFor = 4 },
    },
    {
        name = 'Bancos',
        title = 'Bancos',
        desc = "Ver bancos variados",
        { propModel = "p_bench03x",          displayName = "Banco Caseiro",       costToBuy = 10, sellFor = 8 },
        { propModel = "p_bench09x",          displayName = "Banco de Madeira",    costToBuy = 15, sellFor = 13 },
        { propModel = "p_bench08bx",         displayName = "Banco Vermelho",      costToBuy = 15, sellFor = 13 },
        { propModel = "p_benchannsaloon01x", displayName = "Banco de Madeira Escura", costToBuy = 25, sellFor = 23 },
        { propModel = "p_benchch01x",        displayName = "Banco de Igreja",     costToBuy = 25, sellFor = 23 },
        { propModel = "p_bench15x",          displayName = "Banco Urbano",        costToBuy = 35, sellFor = 33 },
    },
    {
        name = 'Mesas',
        title = 'Mesas',
        desc = "Ver mesas variadas",
        { propModel = "p_table04x",   displayName = "Mesa de Cozinha",               costToBuy = 15, sellFor = 13 },
        { propModel = "p_table55x",   displayName = "Mesa Pintada",                  costToBuy = 30, sellFor = 28 },
        { propModel = "p_table51x",   displayName = "Mesa com Toalha Branca",        costToBuy = 30, sellFor = 28 },
        { propModel = "p_table14x",   displayName = "Mesa com Toalha Colorida",      costToBuy = 25, sellFor = 13 },
        { propModel = "p_table48x",   displayName = "Mesa de Madeira",               costToBuy = 20, sellFor = 18 },
        { propModel = "p_table47x",   displayName = "Mesa de Madeira Pequena",       costToBuy = 15, sellFor = 13 },
        { propModel = "p_table46x",   displayName = "Mesa de Madeira Velha",         costToBuy = 15, sellFor = 13 },
        { propModel = "p_table42_cs", displayName = "Mesa de Canto de Madeira Velha", costToBuy = 10, sellFor = 8 },
        { propModel = "p_tablehob1x", displayName = "Mesa Quebrada",                 costToBuy = 5,  sellFor = 4 },
        { propModel = "p_desk14x",    displayName = "Escrivaninha Envernizada",      costToBuy = 50, sellFor = 45 },
        { propModel = "p_desk04x",    displayName = "Escrivaninha",                  costToBuy = 45, sellFor = 43 },
        { propModel = "p_desk01x",    displayName = "Mesa de Trabalho",              costToBuy = 25, sellFor = 23 },
        { propModel = "s_desk01x",    displayName = "Mesa de Trabalho Velha",        costToBuy = 15, sellFor = 13 },
    },
    {
        name = 'Camas',
        title = 'Camas',
        desc = "Ver camas variadas",
        { propModel = "p_bedrollopen03x",     displayName = "Saco de Dormir Branco",  costToBuy = 10, sellFor = 8 },
        { propModel = "s_bedrollfurlined01x", displayName = "Saco de Dormir Vermelho", costToBuy = 10, sellFor = 8 },
        { propModel = "p_bedindian01x",       displayName = "Cama Feita em Casa",     costToBuy = 10, sellFor = 8 },
        { propModel = "p_bed03x",             displayName = "Cama Velha",             costToBuy = 15, sellFor = 13 },
        { propModel = "p_bed14x",             displayName = "Cama Suja",              costToBuy = 15, sellFor = 13 },
        { propModel = "p_bed21x",             displayName = "Cama com Cobertor Azul", costToBuy = 30, sellFor = 28 },
        { propModel = "p_bed17x",             displayName = "Cama com Cobertor Marrom", costToBuy = 30, sellFor = 28 },
        { propModel = "p_bed05x",             displayName = "Cama com Cobertor de Renda", costToBuy = 40, sellFor = 38 },
        { propModel = "p_bed22x",             displayName = "Cama Alta",              costToBuy = 50, sellFor = 48 },
        { propModel = "p_bed20madex",         displayName = "Cama de Casal",          costToBuy = 80, sellFor = 78 },
    },
    {
        name = 'Armazenamento',
        title = 'Armazenamento',
        desc = "Ver armários variados",
        { propModel = "p_cupboard01x",     displayName = "Armário de Parede Antigo",      costToBuy = 5,  sellFor = 4 },
        { propModel = "p_cupboard06x",     displayName = "Armário Azul Antigo",          costToBuy = 10, sellFor = 8 },
        { propModel = "p_cupboard03x",     displayName = "Armário Branco Antigo",        costToBuy = 10, sellFor = 8 },
        { propModel = "p_bookcase01x",     displayName = "Bufê Grande",                  costToBuy = 25, sellFor = 23 },
        { propModel = "p_cupboard02x",     displayName = "Bufê Pequeno",                 costToBuy = 20, sellFor = 18 },
        { propModel = "p_shelfwall02x",    displayName = "Prateleira de Madeira",        costToBuy = 5,  sellFor = 4 },
        { propModel = "p_kitchenhutch01x", displayName = "Bufê de Cozinha",              costToBuy = 30, sellFor = 28 },
        { propModel = "p_shelf06x",        displayName = "Bufê de Madeira Escura",       costToBuy = 40, sellFor = 38 },
        { propModel = "p_dresser11x",      displayName = "Cômoda Escura",                costToBuy = 35, sellFor = 33 },
        { propModel = "p_shelfwall05x",    displayName = "Prateleira Envernizada",       costToBuy = 10, sellFor = 9 },
        { propModel = "p_armoir08x",       displayName = "Guarda-Roupa Pequeno",         costToBuy = 30, sellFor = 28 },
        { propModel = "p_armoir04x",       displayName = "Guarda-Roupa Grande",          costToBuy = 40, sellFor = 38 },
        { propModel = "p_armoir07x",       displayName = "Guarda-Roupa Envernizado",     costToBuy = 50, sellFor = 48 },
        
    },
    {
        name = 'Decoração',
        title = 'Decoração',
        desc = "Ver itens diversos",
        { propModel = "p_candlegroup05x",      displayName = "Vela",                      costToBuy = 1,  sellFor = 0 },
        { propModel = "p_candlestand",         displayName = "Castiçal",                 costToBuy = 3,  sellFor = 2 },
        { propModel = "s_interact_lantern01x", displayName = "Lanterna",                 costToBuy = 10, sellFor = 9 },
        { propModel = "p_lanternstick09x",     displayName = "Lanterna com Suporte",     costToBuy = 10, sellFor = 9 },
        { propModel = "p_lamp25x",             displayName = "Lamparina com Abajur",     costToBuy = 10, sellFor = 9 },
        { propModel = "p_oillamp01x",          displayName = "Lamparina a Gás",          costToBuy = 8,  sellFor = 7 },
        { propModel = "p_dressmirror01x",      displayName = "Espelho Grande",           costToBuy = 35, sellFor = 33 },
        { propModel = "p_mirror03x",           displayName = "Espelho Comum",            costToBuy = 20, sellFor = 18 },
        { propModel = "p_mirror_shave01x",     displayName = "Espelho de Barbear",       costToBuy = 10, sellFor = 9 },
        { propModel = "p_hatstand01xng",       displayName = "Cabide de Pé",             costToBuy = 15, sellFor = 13 },
        { propModel = "p_coatrack04x",         displayName = "Cabide de Parede",         costToBuy = 10, sellFor = 9 },
        { propModel = "p_alarmclock01x",       displayName = "Despertador",              costToBuy = 35, sellFor = 33 },
        { propModel = "val_bank_clock",        displayName = "Relógio de Parede",        costToBuy = 40, sellFor = 38 },
        { propModel = "p_wallclocklrg01x",     displayName = "Relógio Grande",           costToBuy = 50, sellFor = 48 },
        { propModel = "p_pot_flowerarng01x",   displayName = "Buquê no Vaso",            costToBuy = 15, sellFor = 13 },
        { propModel = "p_pot_flowerarng05x",   displayName = "Flores no Vaso",           costToBuy = 15, sellFor = 13 },
        { propModel = "p_pot_flowerarng07x",   displayName = "Planta no Vaso",           costToBuy = 15, sellFor = 13 },
        { propModel = "p_pot_flowerarng11x",   displayName = "Flores no Copo",           costToBuy = 3,  sellFor = 2 },
        { propModel = "p_gunsmithprops20x",    displayName = "Chifres de Veado",         costToBuy = 20, sellFor = 18 },
        { propModel = "p_gunsmithprops17x",    displayName = "Chifres de Veado Grandes", costToBuy = 30, sellFor = 28 },
        
    },
    {
        name = 'Cozinha',
        title = 'Cozinha',
        desc = "Ver itens variados de cozinha",
        { propModel = "p_sink02x",         displayName = "Pia Grande com Torneira",     costToBuy = 90,  sellFor = 88 },
        { propModel = "p_stove04x",        displayName = "Fogão Burguês",               costToBuy = 100, sellFor = 98 },
        { propModel = "p_stove06x",        displayName = "Fogão Antigo",                costToBuy = 120, sellFor = 118 },
        { propModel = "p_stove01x",        displayName = "Fogão Grande",                costToBuy = 150, sellFor = 148 },
        { propModel = "p_cookingtools01x", displayName = "Utensílios de Parede",        costToBuy = 10,  sellFor = 9 },
        
    },
    {
        name = 'Banheiro',
        title = 'Banheiro',
        desc = "Ver itens variados de banheiro",
        { propModel = "p_washtub02x",            displayName = "Banheira de Banho",           costToBuy = 10,  sellFor = 9 },
        { propModel = "p_washbasin01x",          displayName = "Bacia Antiga",                costToBuy = 15,  sellFor = 13 },
        { propModel = "p_washbasndoctor01x",     displayName = "Bacia com Espelho",          costToBuy = 25,  sellFor = 23 },
        { propModel = "p_sink03x",               displayName = "Bacia de Cerâmica",           costToBuy = 35,  sellFor = 33 },
        { propModel = "p_bath02x",               displayName = "Banheira de Bronze",          costToBuy = 250, sellFor = 248 },
        { propModel = "p_val_hotel_int_tub_01x", displayName = "Banheira com Acabamento em Madeira", costToBuy = 100, sellFor = 98 },
        { propModel = "p_toiletchair01x",        displayName = "Vaso Sanitário Noturno",      costToBuy = 15,  sellFor = 13 },

    },
    {
        name = 'Quintal',
        title = 'Quintal',
        desc = "Ver itens variados de quintal",
        { propModel = "p_waterpump01x",      displayName = "Hidrante de Ferro",         costToBuy = 80, sellFor = 78 },
        { propModel = "p_wellpumpnbx01x",    displayName = "Hidrante Antigo",           costToBuy = 60, sellFor = 58 },
        { propModel = "p_hng_toi",           displayName = "Privada Externa",           costToBuy = 30, sellFor = 28 },
        { propModel = "p_hitchingpost01x",   displayName = "Poste de Amarrar Grande",   costToBuy = 10, sellFor = 9 },
        { propModel = "p_hitchingpost04x",   displayName = "Poste de Amarrar Pequeno",  costToBuy = 5,  sellFor = 4 },
        { propModel = "p_toolbox01x",        displayName = "Caixa de Ferramentas",      costToBuy = 10, sellFor = 9 },
        { propModel = "p_group_barrelcor01", displayName = "Barril com Ferramentas",    costToBuy = 10, sellFor = 9 },
    }
    
}